### ISSUE TITLE
Initial Review

### ISSUE THREAD

**Issue by GLabat** [imaginoCDP/stripo-bynder-extension#1]
- Add a README.md explaining how to build & deploy the extension

## In `createBynderBlockExtension.js`

- No need for "Settings" in   name: 'BynderBlockSettings'
- Do we need all the options like `settingsCssPath`?

## In `modal_window.js`

- Add desc of `openBynder` method
- Explain the link between what is done in `onSuccess: (assets, additionalInfo)` and the `layout/defaultLayout.html`

**Comment by imaginoCDP** [comment]
https://github.com/imaginoCDP/stripo-bynder-extension/blob/e0d101fbba7b6f034ce787745fdc935f0faf22ce/src/js/createBynderBlockExtension.js#L17
should throw if the `token` is null

---

https://github.com/imaginoCDP/stripo-bynder-extension/blob/e0d101fbba7b6f034ce787745fdc935f0faf22ce/src/js/createBynderBlockExtension.js#L16
should throw if `portalUrl` is null

---

https://github.com/imaginoCDP/stripo-bynder-extension/blob/e0d101fbba7b6f034ce787745fdc935f0faf22ce/src/js/createBynderBlockExtension.js#L21
We should ensure that `block.find('>.esd-structure-type')` exists before calling `html` method.

---

https://github.com/imaginoCDP/stripo-bynder-extension/blob/e0d101fbba7b6f034ce787745fdc935f0faf22ce/src/js/createBynderBlockExtension.js#L26
`openBynder` should be write with object parameter

---

https://github.com/imaginoCDP/stripo-bynder-extension/blob/e0d101fbba7b6f034ce787745fdc935f0faf22ce/src/js/createBynderBlockExtension.js#L32
Add a comment: '// ## we should test to display the bynder icon here'

---

 https://github.com/imaginoCDP/stripo-bynder-extension/blob/e0d101fbba7b6f034ce787745fdc935f0faf22ce/src/js/index.js#L16
Should be a constant: const GLOBAL_EXTENSION_NAME = 'bynderBlockExtension'  in camel-case

**Comment by RobinLallier** [comment]
## In Index.js

- No need to repeat `Object.assign({ stripoConfig: stripoConfig })`. `Object.assign({stripoConfig})` is enough
- I don't really get why we are filling some empty/null values from `stripoDefaultExtension` if we're overriding them right afterwards. My take is we could remove this file, and add at the end of createBynderBlockExtension the missing default values with a comment "// Values required by Stripo"

## .tif & .eps images

Is there a parameter in bynder that could allow us to filter the images from the bynder integration if we already know the support will be partial? If so we can remove the TAG_NAME_IMAGE_NOT_SUPPORTED logic

**Comment by GLabat** [comment]
> https://github.com/imaginoCDP/stripo-bynder-extension/blob/e0d101fbba7b6f034ce787745fdc935f0faf22ce/src/js/createBynderBlockExtension.js#L17
> 
> 
> should throw if the `token` is null

I disagree on that. The `useBynderConfig` hook is in charge of this. So as soon as `bynderConfig` is defined, both `token` and `portalUrl` are guaranteed to be defined.

`useBynderConfig` could throw anyway and if so, the caller of this hook (`Stripo` component) should handle the error, for ex by disabling the Bynder block with a dedicated tooltip, to mimic what is done in the Monaco editor case.

**Comment by Elyes-nk** [comment]
@imaginoCDP No need to throw since the block is not displayed if config is not defined 

in `createBynderBlockExtension.js`
```js
isEnabled: () => hasCredentials, // Disable bynder block if no credentials
```

**Comment by Elyes-nk** [comment]
> ## .tif & .eps images
> Is there a parameter in bynder that could allow us to filter the images from the bynder integration if we already know the support will be partial? If so we can remove the TAG_NAME_IMAGE_NOT_SUPPORTED logic

For now there is no way to add a default filter on images in bynder.
